root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd/app"
bin = "tmp/main"
full_bin = "./tmp/main -dev=true"
include_ext = ["go", "html", "css", "js", "toml"]
exclude_dir = ["tmp", "vendor", ".git"]
exclude_file = [".gitignore"]
exclude_regex = ["_test\\.go"]
exclude_unchanged = true
follow_symlink = true
log = "air.log"
poll = false
poll_interval = 500
stop_on_error = true
send_interrupt = true
kill_delay = 500
rerun = true
rerun_delay = 1000

[log]
time = true
main_only = false

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true