# fly.toml app configuration file generated for rate-calculator-hidden-butterfly-9065 on 2025-06-12T01:22:23+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rate-calculator'
primary_region = 'otp'

[build]
  [build.args]
    GO_VERSION = '1.24.3'

[env]
  PORT = '3000'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
