# Fly.io deployment configuration for Rate Calculator
app = 'rate-calculator'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[env]
  # App automatically uses PORT environment variable
  # No need to set it here as Fly.io provides it

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

# Secrets to set via: fly secrets set COOKIE_SESSION_KEY=$(openssl rand -base64 32) 