# fly.toml app configuration file generated for rate-calculator on 2025-06-05T02:52:16+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rate-calculator'
primary_region = 'otp'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
